In [1]:
import pandas as pd
data_frame = pd.DataFrame([1, 2, 3, 4, 5])

In [12]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\hp\appdata\roaming\python\python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\users\hp\appdata\roaming\python\python314\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\roaming\python\python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

# Capital 'F' and square brackets []
data_frame = pd.DataFrame([1, 2, 3, 4, 5])
print(data_frame)

   0
0  1
1  2
2  3
3  4
4  5

In [4]:
df = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35], 'salary': [50000, 60000, None],
                   'department': ['HR', 'IT', 'Finance'], 'manager': ['John', 'Jane', None], 'skills': ['Python', 'Java', 'SQL']})

In [5]:
df.fillna(value={'salary': df['salary'].mean()}, inplace=True)

      name  age   salary department manager  skills
0    Alice   25  50000.0         HR    John  Python
1      Bob   30  60000.0         IT    Jane    Java
2  Charlie   35  55000.0    Finance     NaN     SQL

In [6]:
df.dropna(subset=['salary'], inplace=True)

In [7]:
department_df = pd.DataFrame({'id': [1, 2, 3],
                              'department': ['HR', 'IT', 'Finance'], 
                              'location': ['New York', 'San Francisco', 'Chicago']})

In [8]:
df_merged = pd.merge(df, department_df, on='department', how='outer')
df_merged

      name  age   salary department manager  skills  id       location
0  Charlie   35  55000.0    Finance     NaN     SQL   3        Chicago
1    Alice   25  50000.0         HR    John  Python   1       New York
2      Bob   30  60000.0         IT    Jane    Java   2  San Francisco

In [9]:
df = pd.DataFrame({'name': ['Ali', 'Bobi', 'Chad'], 'age': [5, 35, 45], 'salary': [None, 60000, None],
                   'department': ['HR', 'IT', 'Management'], 'manager': ['John', 'Janice', None], 'skills': ['Python', 'Java', 'SQL']})

In [10]:
df_additional = pd.DataFrame({'name': ['David', 'Eva'], 'age': [28, 32], 'salary': [55000, 65000],
                              'department': ['Finance', 'IT'], 'manager': ['Mike', 'Sara'], 'skills': ['C++', 'JavaScript']})
df_additional

    name  age  salary department manager      skills
0  David   28   55000    Finance    Mike         C++
1    Eva   32   65000         IT    Sara  JavaScript

In [11]:
df_new = pd.concat([df, df_additional], ignore_index=True)
df_new

    name  age   salary  department manager      skills
0    Ali    5      NaN          HR    John      Python
1   Bobi   35  60000.0          IT  Janice        Java
2   Chad   45      NaN  Management     NaN         SQL
3  David   28  55000.0     Finance    Mike         C++
4    Eva   32  65000.0          IT    Sara  JavaScript

In [ ]:
s1 = p